### ISSUE TITLE
Easily switch / exchange base map

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/c2app#54]
Can we use PDOK: https://www.pdok.nl/-/vector-tiles-brt-en-bgt-via-pdok for NL
https://geodata.nationaalgeoregister.nl/beta/topotiles/ 

[Demo](http://geodata.nationaalgeoregister.nl/beta/topotiles-viewer/#11.3/52.3471/4.8751)

[How to use](https://github.com/PDOK/vectortiles-bgt-brt)

**Comment by timovdk** [comment]
Implemented.
