### ISSUE TITLE
Add aerial map (via WMS)

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/c2app#56]
Is it possible to add a WMS layer as basemap, or is there a mapbox style that we can overlay the road and house contours (and the rest transparent) on top of aerial maps?

25cm RGB luchtfoto’s
WMS: https://service.pdok.nl/hwh/luchtfotorgb/wms/v1_0?&request=GetCapabilities&service=wms
WMTS: https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?&request=GetCapabilities&service=wmts

25cm Infrarood luchtfoto’s
WMS: https://service.pdok.nl/hwh/luchtfotocir/wms/v1_0?&request=GetCapabilities&service=wms
WMTS: https://service.pdok.nl/hwh/luchtfotocir/wmts/v1_0?&request=GetCapabilities&service=wmts

**Comment by timovdk** [comment]
![image](https://user-images.githubusercontent.com/5330531/125942057-786433b9-8dda-494e-bcd9-55c4e4506565.png)
